export type TriviaType = {
  value: string;
  label: string;
};

export const trivias: TriviaType[] = [
  { value: 'Animals', label: 'Animals' },
  { value: 'Architecture', label: 'Architecture' },
  { value: 'Art', label: 'Art' },
  { value: 'Astronomy', label: 'Astronomy' },
  { value: 'Books', label: 'Books' },
  { value: 'Business', label: 'Business' },
  { value: 'Celebrities', label: 'Celebrities' },
  { value: 'Cinema', label: 'Cinema' },
  { value: 'Cuisine', label: 'Cuisine' },
  { value: 'Culture', label: 'Culture' },
  { value: 'Dance', label: 'Dance' },
  { value: 'Economics', label: 'Economics' },
  { value: 'Fashion', label: 'Fashion' },
  { value: 'Geography', label: 'Geography' },
  { value: 'History', label: 'History' },
  { value: 'Languages', label: 'Languages' },
  { value: 'Literature', label: 'Literature' },
  { value: 'Mathematics', label: 'Mathematics' },
  { value: 'Medicine', label: 'Medicine' },
  { value: 'Music', label: 'Music' },
  { value: 'Nature', label: 'Nature' },
  { value: 'Philosophy', label: 'Philosophy' },
  { value: 'Politics', label: 'Politics' },
  { value: 'Psychology', label: 'Psychology' },
  { value: 'Religions', label: 'Religions' },
  { value: 'Science', label: 'Science' },
  { value: 'Sports', label: 'Sports' },
  { value: 'Technology', label: 'Technology' },
  { value: 'Television', label: 'Television' },
  { value: 'Theatre', label: 'Theatre' },
  { value: 'Travel', label: 'Travel' },
  { value: 'Vehicles', label: 'Vehicles' },
  { value: 'VideoGames', label: 'Video Games' },
  { value: 'Weather', label: 'Weather' },
  { value: 'WineAndBeverages', label: 'Wine & Beverages' },
  { value: 'WorldRecords', label: 'World Records' },
  { value: 'Zoology', label: 'Zoology' },
];
